# Generated by Django 5.0.2 on 2024-03-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Título')),
                ('status', models.CharField(choices=[('TODO', 'A fazer'), ('IN_PROGRESS', 'Em progresso'), ('DONE', 'Concluída')], default='TODO', max_length=50, verbose_name='Situação')),
                ('description', models.TextField(blank=True, max_length=250, null=True, verbose_name='Descrição')),
            ],
        ),
    ]
